## Numpy Section

In [1]:
import pandas as pd
import numpy as np

### Data Types & Attributes

In [7]:
# NumPy's main datatype is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [8]:
type(a1)

numpy.ndarray

In [9]:
a2 = np.array([[1, 2, 3],
               [4, 5, 6]])

a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])

In [10]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [23]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [22]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('int32'), dtype('int32'))

In [24]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [29]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [37]:
# Create a DataFrame from a NumPy array 
df = pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  6

### Create NumPy arrays

In [39]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [40]:
sample_array.dtype

dtype('int32')

In [59]:
ones = np.ones((2,3))
zeros = np.zeros((2,3))
ones, zeros

(array([[1., 1., 1.],
        [1., 1., 1.]]),
 array([[0., 0., 0.],
        [0., 0., 0.]]))

In [60]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [77]:
random_array = np.random.randint(0, 10, (3, 5))
random_array

array([[4, 8, 3, 1, 4],
       [5, 1, 9, 9, 2],
       [1, 8, 6, 7, 5]])

In [72]:
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.00646762, 0.4477953 , 0.81102435],
       [0.30836775, 0.60312211, 0.26667629],
       [0.58142944, 0.51446991, 0.71631487],
       [0.62898805, 0.11336812, 0.8539299 ],
       [0.91786219, 0.00821483, 0.18520323]])

In [74]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.6432832 , 0.44559663, 0.27023238],
       [0.87457404, 0.56435021, 0.63221069],
       [0.0043699 , 0.16307489, 0.77189032],
       [0.22810367, 0.58193927, 0.63613924],
       [0.35959342, 0.84002292, 0.42492773]])

In [131]:
# Pseudo-random numbers
np.random.seed(99999)

random_array_4 = np.random.randint(10, size = (5,3))
random_array_4

array([[0, 3, 1],
       [8, 1, 3],
       [8, 5, 6],
       [0, 6, 0],
       [4, 0, 9]])

In [127]:
np.random.seed(7)
random_array_5 = np.random.random((5,3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [128]:
random_array_5 = np.random.random((5,3))
random_array_5

array([[0.90959353, 0.21338535, 0.45212396],
       [0.93120602, 0.02489923, 0.60054892],
       [0.9501295 , 0.23030288, 0.54848992],
       [0.90912837, 0.13316945, 0.52341258],
       [0.75040986, 0.66901324, 0.46775286]])

### Viewing arrays and matrices

In [132]:
np.unique(random_array_4)

array([0, 1, 3, 4, 5, 6, 8, 9])

In [137]:
a1

array([1, 2, 3])

In [134]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [135]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [138]:
a4 = np.random.randint(10, size = (2, 3, 4, 5))
a4

array([[[[2, 0, 0, 5, 0],
         [0, 8, 1, 0, 9],
         [7, 1, 8, 9, 5],
         [8, 3, 4, 2, 1]],

        [[5, 5, 8, 3, 4],
         [6, 9, 6, 9, 4],
         [6, 5, 5, 8, 8],
         [7, 4, 0, 9, 2]],

        [[0, 7, 2, 8, 1],
         [2, 9, 4, 4, 4],
         [3, 3, 4, 1, 0],
         [1, 3, 0, 5, 8]]],


       [[[7, 7, 5, 4, 6],
         [8, 7, 6, 4, 7],
         [4, 4, 4, 2, 5],
         [7, 2, 2, 0, 8]],

        [[1, 5, 5, 5, 6],
         [9, 0, 7, 7, 6],
         [2, 5, 0, 9, 1],
         [0, 6, 9, 9, 3]],

        [[2, 3, 2, 4, 0],
         [6, 0, 2, 0, 6],
         [9, 5, 4, 1, 7],
         [5, 7, 8, 2, 7]]]])

In [139]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [157]:
a4[1:, 2:, 0, :4]

array([[[2, 3, 2, 4]]])

### Manipulate data

In [20]:
# Arithmetic 

a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [28]:
ones = np.ones(3)
ones
zeros = np.zeros(3)
zeros

array([0., 0., 0.])

In [26]:
a1 + ones

array([2., 3., 4.])

In [11]:
a1 - ones

array([0., 1., 2., 3.])

In [29]:
a1 * zeros

array([0., 0., 0.])

In [37]:
a2 = np.array([[1, 2, 3],
               [4, 5, 6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
a1 * a2

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [58]:
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])
np.reshape(a2, (6))
# a2 * a3

array([1, 2, 3, 4, 5, 6])

In [59]:
a1 / ones

array([1., 2., 3.])

In [61]:
a2 / a1

array([[1. , 1. , 1. ],
       [4. , 2.5, 2. ]])

In [60]:
a2 // a1

array([[1, 1, 1],
       [4, 2, 2]])

In [63]:
a2 ** a1

array([[  1,   4,  27],
       [  4,  25, 216]])

In [64]:
np.square(a2)

array([[ 1,  4,  9],
       [16, 25, 36]])